version: 0.2
phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
  build:
    commands:
      - echo "Build started for Next.js on `date`"
      - |
        if [ ! -f "Dockerfile" ]; then
          echo "Creating default Dockerfile for Next.js..."
          cat > Dockerfile <<'DOCKER'
FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:18-alpine AS runner
WORKDIR /app
ENV NODE_ENV production
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
EXPOSE 3000
CMD ["node", "server.js"]
DOCKER
        fi
      - docker build -t $ECR_IMAGE_URI .
  post_build:
    commands:
      - docker push $ECR_IMAGE_URI