version: 0.2
phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
      - echo "Restoring .env file from SSM if provided..."
      - if [ -n "$DOTENV_BLOB_SSM_PATH" ]; then aws ssm get-parameter --name "$DOTENV_BLOB_SSM_PATH" --with-decryption --query Parameter.Value --output text > .env && echo "Successfully restored .env file."; else echo ".env file not provided, skipping."; fi
  build:
    commands:
      - echo "Build started for Node.js on `date`"
      - |
        if [ ! -f "Dockerfile" ]; then
          echo "Creating default Dockerfile for Node.js..."
          cat > Dockerfile <<'DOCKER'
FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production
COPY . .
EXPOSE 3000
CMD ["npm", "start"]
DOCKER
        fi
      - docker build -t $ECR_IMAGE_URI .
  post_build:
    commands:
      - docker push $ECR_IMAGE_URI