version: 0.2
phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
  build:
    commands:
      - echo "Build started for Node.js on `date`"
      - |
        if [ ! -f "Dockerfile" ]; then
          echo "Creating default Dockerfile for Node.js..."
          cat > Dockerfile <<'DOCKER'
FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production
COPY . .
EXPOSE 3000
CMD ["npm", "start"]
DOCKER
        fi
      - docker build -t $ECR_IMAGE_URI .
  post_build:
    commands:
      - docker push $ECR_IMAGE_URI