version: 0.2
phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
  build:
    commands:
      - echo "Build started for Spring Boot on `date`"
      - echo "Current directory:" && pwd && ls -la
      - |
        BUILD_DIR="."
        if [ -n "$SOURCE_DIR" ]; then
          echo "Source directory specified: $SOURCE_DIR"
          BUILD_DIR="$SOURCE_DIR"
          cd $SOURCE_DIR
          echo "Changed to directory: $SOURCE_DIR" && pwd && ls -la
        fi
      - |
        echo "Building Spring Boot application..."
        if [ -f "build.gradle" ]; then
          echo "Found build.gradle, building with Gradle"
          chmod +x gradlew 2>/dev/null || echo "No gradlew found, using system gradle"
          if [ -f "gradlew" ]; then
            ./gradlew build -x test --no-daemon
          else
            gradle build -x test
          fi
        else
          echo "No build.gradle found in current directory"
          exit 1
        fi
      - |
        echo "Checking for Dockerfile..."
        DOCKERFILE_PATH=""
        if [ -f "Dockerfile" ]; then
          DOCKERFILE_PATH="Dockerfile"
          echo "Found Dockerfile in current directory"
        elif [ -f "../Dockerfile" ]; then
          DOCKERFILE_PATH="../Dockerfile"
          echo "Found Dockerfile in parent directory"
        else
          echo "No Dockerfile found - creating default Dockerfile for Spring Boot..."
          echo 'FROM eclipse-temurin:17-jre-alpine' > Dockerfile
          echo 'WORKDIR /app' >> Dockerfile
          echo 'COPY build/libs/*.jar app.jar' >> Dockerfile
          echo 'EXPOSE 8080' >> Dockerfile
          echo 'ENTRYPOINT ["java", "-jar", "app.jar"]' >> Dockerfile
          DOCKERFILE_PATH="Dockerfile"
          echo "Created default Dockerfile"
        fi
        echo "Using Dockerfile at: $DOCKERFILE_PATH"
      - |
        echo "Building Docker image..."
        if [ -n "$SOURCE_DIR" ]; then
          echo "Building from subdirectory context: $SOURCE_DIR"
          cd $CODEBUILD_SRC_DIR
          docker build -f $SOURCE_DIR/$DOCKERFILE_PATH -t $ECR_IMAGE_URI $SOURCE_DIR
        else
          echo "Building from root directory"
          docker build -f $DOCKERFILE_PATH -t $ECR_IMAGE_URI .
        fi
  post_build:
    commands:
      - docker push $ECR_IMAGE_URI