version: 0.2
phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
  build:
    commands:
      - echo "Build started for Spring Boot on `date`"
      - |
        if [ -n "$SOURCE_DIR" ]; then
          echo "Changing to source directory: $SOURCE_DIR"
          cd $SOURCE_DIR
        fi
      - |
        if [ -f "build.gradle" ]; then
          chmod +x gradlew
          ./gradlew build -x test --no-daemon
        fi
      - |
        DOCKERFILE_PATH=""
        if [ -f "Dockerfile" ]; then
          DOCKERFILE_PATH="./Dockerfile"
          echo "Found Dockerfile in current directory"
        elif [ -f "../Dockerfile" ]; then
          DOCKERFILE_PATH="../Dockerfile"
          echo "Found Dockerfile in parent directory"
        else
          echo "No Dockerfile found - creating default Dockerfile for Spring Boot..."
          cat > Dockerfile <<'DOCKER'
FROM openjdk:17-jre-slim
WORKDIR /app
COPY build/libs/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
DOCKER
          DOCKERFILE_PATH="./Dockerfile"
        fi
        echo "Using Dockerfile at: $DOCKERFILE_PATH"
      - |
        if [ -n "$SOURCE_DIR" ]; then
          docker build -t $ECR_IMAGE_URI $SOURCE_DIR
        else
          docker build -t $ECR_IMAGE_URI .
        fi
  post_build:
    commands:
      - docker push $ECR_IMAGE_URI