version: 0.2
phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
  build:
    commands:
      - echo "Build started for Spring Boot on `date`"
      - |
        if [ -f "build.gradle" ]; then
          chmod +x gradlew
          ./gradlew build -x test --no-daemon
        fi
      - |
        if [ ! -f "Dockerfile" ]; then
          echo "Creating default Dockerfile for Spring Boot..."
          cat > Dockerfile <<'DOCKER'
FROM openjdk:17-jre-slim
WORKDIR /app
COPY build/libs/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
DOCKER
        fi
      - docker build -t $ECR_IMAGE_URI .
  post_build:
    commands:
      - docker push $ECR_IMAGE_URI